site_name: GitHub vs GitLabs
site_dir: public
theme:
  #name: material
  name: readthedocs
nav:
    - index.md
    - github.md
    - gitlabs.md
    - readthedocs.md
    - jenkins-ci.md
    - git-mirror.md
